"""
Training loop for the partial-conv inpainting model.

Run from the repo root (D:\\DL_project5\\):
  python models/train.py --overfit_test        # quick sanity check
  python models/train.py --epochs 20           # full training

Assumes data/train_paths.txt etc. and data/fixed_masks_val_medium.pt
have already been generated by the scripts under data/.
"""
import os
import sys
import time
import argparse
from pathlib import Path

# Make sure we can import utils/ from the repo root no matter where
# this script is called from.
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

import torch
from torch.utils.data import DataLoader, Subset
import torchvision.utils as vutils

from utils.dataset import InpaintingTrainDataset, FixedMaskInpaintingDataset

from models.model import PConvUNet
from models.losses import InpaintingLoss


def load_paths(txt_path):
    with open(txt_path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--train_paths', type=str, default='./data/train_paths.txt')
    p.add_argument('--val_paths', type=str, default='./data/val_paths.txt')
    p.add_argument('--val_masks', type=str, default='./data/fixed_masks_val_medium.pt',
                   help='fixed mask file used during validation (medium regime)')
    p.add_argument('--image_size', type=int, default=256)
    p.add_argument('--batch_size', type=int, default=4)
    p.add_argument('--lr', type=float, default=2e-4)
    p.add_argument('--epochs', type=int, default=30)
    p.add_argument('--num_workers', type=int, default=0,
                   help='keep this at 0 on Windows to avoid multiprocessing issues')
    p.add_argument('--save_dir', type=str, default='./checkpoints/pconv')
    p.add_argument('--log_dir', type=str, default='./logs/pconv')
    p.add_argument('--sample_dir', type=str, default='./samples/pconv')
    p.add_argument('--resume', type=str, default=None)
    p.add_argument('--overfit_test', action='store_true',
                   help='train on 50 images for 2 epochs, just to check the pipeline')
    p.add_argument('--use_amp', action='store_true', default=True,
                   help='use bf16 mixed precision (faster, uses less memory)')
    return p.parse_args()


@torch.no_grad()
def save_sample_images(model, dataset, device, save_path, n_samples=4):
    """Grid image with [gt | masked | mask | output] rows for eyeballing progress."""
    model.eval()
    rows = []
    for i in range(min(n_samples, len(dataset))):
        sample = dataset[i]
        gt = sample['gt'].unsqueeze(0).to(device)
        hole_mask = sample['mask'].unsqueeze(0).to(device)
        masked = sample['masked'].unsqueeze(0).to(device)

        out = model(masked, hole_mask)
        # Composite: keep the observed pixels, use the model only for the hole
        hole_3ch = hole_mask.expand_as(gt)
        composite = (1 - hole_3ch) * gt + hole_3ch * out
        composite = composite.clamp(0, 1)

        mask_vis = hole_3ch
        rows.append(torch.cat([gt, masked, mask_vis, composite], dim=3))

    grid = torch.cat(rows, dim=2)
    vutils.save_image(grid.clamp(0, 1), save_path)
    model.train()


def main():
    args = parse_args()

    Path(args.save_dir).mkdir(exist_ok=True, parents=True)
    Path(args.log_dir).mkdir(exist_ok=True, parents=True)
    Path(args.sample_dir).mkdir(exist_ok=True, parents=True)

    log_file = open(os.path.join(args.log_dir, 'train_log.txt'), 'a', encoding='utf-8')
    def log(msg):
        print(msg)
        log_file.write(msg + '\n')
        log_file.flush()

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    log(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] training started")
    log(f"device: {device}")
    if torch.cuda.is_available():
        log(f"gpu: {torch.cuda.get_device_name(0)}")
        log(f"memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # Training data: random masks from all three regimes with equal probability
    train_paths = load_paths(args.train_paths)
    train_dataset = InpaintingTrainDataset(
        train_paths,
        image_size=args.image_size,
        regime="mixed",
        mixed_probs=(1/3, 1/3, 1/3),
    )

    # Validation: fixed medium masks for reproducibility
    val_paths = load_paths(args.val_paths)
    val_dataset = FixedMaskInpaintingDataset(
        val_paths,
        fixed_masks_path=args.val_masks,
        image_size=args.image_size,
    )

    if args.overfit_test:
        train_dataset = Subset(train_dataset, range(50))
        val_dataset = Subset(val_dataset, range(min(10, len(val_dataset))))
        args.epochs = 2
        log("overfit test mode: 50 images, 2 epochs")

    log(f"train: {len(train_dataset)}, val: {len(val_dataset)}")

    train_loader = DataLoader(train_dataset, batch_size=args.batch_size,
                              shuffle=True, num_workers=args.num_workers,
                              pin_memory=True, drop_last=True)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size,
                            shuffle=False, num_workers=args.num_workers,
                            pin_memory=True)

    model = PConvUNet().to(device)
    n_params = sum(p.numel() for p in model.parameters())
    log(f"model params: {n_params / 1e6:.2f} M")

    loss_fn = InpaintingLoss(
        w_hole=6.0, w_valid=1.0, w_perceptual=0.05,
        w_style=120.0, w_tv=0.1,
        use_style=True, use_tv=True,
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    # Optional resume from checkpoint
    start_epoch = 0
    best_val_loss = float('inf')
    if args.resume and os.path.exists(args.resume):
        ckpt = torch.load(args.resume, map_location=device)
        model.load_state_dict(ckpt['model'])
        optimizer.load_state_dict(ckpt['optimizer'])
        start_epoch = ckpt['epoch'] + 1
        best_val_loss = ckpt.get('best_val_loss', float('inf'))
        log(f"resuming from epoch {start_epoch}")

    for epoch in range(start_epoch, args.epochs):
        model.train()
        epoch_start = time.time()
        running_loss = 0.0
        n_batches = 0

        for batch_idx, batch in enumerate(train_loader):
            gt = batch['gt'].to(device)
            hole_mask = batch['mask'].to(device)
            masked = batch['masked'].to(device)

            optimizer.zero_grad()
            if args.use_amp:
                # bf16 rather than fp16; more stable on Blackwell and good enough
                with torch.amp.autocast('cuda', dtype=torch.bfloat16):
                    output = model(masked, hole_mask)
                    total_loss, loss_dict = loss_fn(output, gt, hole_mask)
                total_loss.backward()
                optimizer.step()
            else:
                output = model(masked, hole_mask)
                total_loss, loss_dict = loss_fn(output, gt, hole_mask)
                total_loss.backward()
                optimizer.step()

            running_loss += total_loss.item()
            n_batches += 1

            if batch_idx % 50 == 0:
                log(f"  Epoch [{epoch+1}/{args.epochs}] Batch [{batch_idx}/{len(train_loader)}] "
                    f"loss={total_loss.item():.4f} "
                    f"(hole={loss_dict['hole']:.4f}, valid={loss_dict['valid']:.4f}, "
                    f"perc={loss_dict['perceptual']:.4f})")

        avg_train_loss = running_loss / max(1, n_batches)

        # Validation pass
        model.eval()
        val_loss = 0.0
        n_val_batches = 0
        with torch.no_grad():
            for batch in val_loader:
                gt = batch['gt'].to(device)
                hole_mask = batch['mask'].to(device)
                masked = batch['masked'].to(device)
                output = model(masked, hole_mask)
                total, _ = loss_fn(output, gt, hole_mask)
                val_loss += total.item()
                n_val_batches += 1
        avg_val_loss = val_loss / max(1, n_val_batches)

        epoch_time = time.time() - epoch_start
        log(f"=== Epoch {epoch+1} done | time={epoch_time:.1f}s | "
            f"train_loss={avg_train_loss:.4f} | val_loss={avg_val_loss:.4f} ===")

        ckpt = {
            'epoch': epoch,
            'model': model.state_dict(),
            'optimizer': optimizer.state_dict(),
            'best_val_loss': best_val_loss,
            'args': vars(args),
        }
        torch.save(ckpt, os.path.join(args.save_dir, 'latest_model.pt'))

        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            ckpt['best_val_loss'] = best_val_loss
            torch.save(ckpt, os.path.join(args.save_dir, 'best_model.pt'))
            log(f"  new best (val_loss={avg_val_loss:.4f})")

        sample_path = os.path.join(args.sample_dir, f'epoch_{epoch+1:03d}.png')
        save_sample_images(model, val_dataset, device, sample_path)
        log(f"  saved samples to {sample_path}")

    log("done.")
    log_file.close()


if __name__ == "__main__":
    main()
